name: Generate and Update GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@master
        with:
          github_user_name: <your-username>
          outputs: github-snake.svg
          outputs_dark: github-snake-dark.svg

      - name: Commit SVG to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add github-snake.svg github-snake-dark.svg
          git commit -m "Update GitHub Snake animation"
          git push
